const fs=require('fs'),path=require('path');
const API_BASE='https://api.excel.gic.mx'; const SITE_ORIGIN='https://excel.gic.mx';
const {renderProductPage}=require('./lib/product-page-template');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8'),write=(file,value)=>{const target=path.join(root,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,value);};
const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
function replaceLinks(file,items){const source=read(file),start='<!-- SEO_PRODUCT_LINKS:START -->',end='<!-- SEO_PRODUCT_LINKS:END -->',a=source.indexOf(start),b=source.indexOf(end);if(a<0||b<0||b<a)throw new Error(`Missing SEO product-link markers in ${file}`);const links=items.map(item=>`<li><a href="${esc(item.url)}" class="text-sm font-semibold text-primary hover:underline">${esc(item.title)}</a></li>`).join('');write(file,`${source.slice(0,a+start.length)}${links}${source.slice(b)}`);}
function sitemap(groups){const entry=group=>`  <url><loc>${esc(group.es)}</loc><xhtml:link rel="alternate" hreflang="es" href="${esc(group.es)}"/>${group.en?`<xhtml:link rel="alternate" hreflang="en" href="${esc(group.en)}"/>`:''}<xhtml:link rel="alternate" hreflang="x-default" href="${esc(group.es)}"/></url>${group.en?`\n  <url><loc>${esc(group.en)}</loc><xhtml:link rel="alternate" hreflang="es" href="${esc(group.es)}"/><xhtml:link rel="alternate" hreflang="en" href="${esc(group.en)}"/><xhtml:link rel="alternate" hreflang="x-default" href="${esc(group.es)}"/></url>`:''}`;return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${groups.map(entry).join('\n')}\n</urlset>\n`;}
function verify(files){for(const file of files){const html=read(file),json=html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);if(!json)throw new Error(`Missing JSON-LD in ${file}`);try{JSON.parse(json[1]);}catch(error){throw new Error(`Invalid JSON-LD in ${file}: ${error.message}`);}if(!/<title>[^<]+<\/title>/.test(html))throw new Error(`Missing title in ${file}`);if(!/<meta name="description" content="[^"]+">/.test(html))throw new Error(`Missing description in ${file}`);}}
async function main(){const response=await fetch(`${API_BASE}/api/goods/catalog`);if(!response.ok)throw new Error(`Catalog request failed: ${response.status}`);const payload=await response.json(),products=Array.isArray(payload.products)?payload.products.filter(p=>p.published!==false):[],translations=JSON.parse(read('i18n/products.en.json')),skipped=[],files=[];let esCount=0,enCount=0;for(const product of products){const translation=translations[product.slug],esUrl=`${SITE_ORIGIN}/p/${encodeURIComponent(product.slug)}/`,enUrl=`${SITE_ORIGIN}/en/p/${encodeURIComponent(product.slug)}/`,hasEn=Boolean(translation);if(!hasEn){console.warn(`Missing English translation for ${product.slug}; skipping EN page.`);skipped.push(product.slug);}write(`p/${product.slug}/index.html`,renderProductPage(product,'es',esUrl,enUrl,hasEn));files.push(`p/${product.slug}/index.html`);esCount++;if(hasEn){write(`en/p/${product.slug}/index.html`,renderProductPage({...product,...translation},'en',esUrl,enUrl,true));files.push(`en/p/${product.slug}/index.html`);enCount++;}}
replaceLinks('index.html',products.map(p=>({title:p.title,url:`/p/${encodeURIComponent(p.slug)}/`})));replaceLinks('en/index.html',products.map(p=>({title:translations[p.slug]?.title||p.title,url:translations[p.slug]?`/en/p/${encodeURIComponent(p.slug)}/`:`/p/${encodeURIComponent(p.slug)}/`})));
const groups=[{es:`${SITE_ORIGIN}/`,en:`${SITE_ORIGIN}/en/`},...products.map(p=>({es:`${SITE_ORIGIN}/p/${encodeURIComponent(p.slug)}/`,en:translations[p.slug]?`${SITE_ORIGIN}/en/p/${encodeURIComponent(p.slug)}/`:''})),{es:`${SITE_ORIGIN}/licencia.html`,en:`${SITE_ORIGIN}/en/licencia.html`}];write('robots.txt','User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /product.html\n\nSitemap: https://excel.gic.mx/sitemap.xml\n');write('sitemap.xml',sitemap(groups));verify(files);console.log(`ES pages written: ${esCount}`);console.log(`EN pages written: ${enCount}`);console.log(`Skipped for missing translation: ${skipped.length?skipped.join(', '):'none'}`);console.log(`Total sitemap URL count: ${groups.reduce((count,group)=>count+1+(group.en?1:0),0)}`);}
main().catch(error=>{console.error(`Generation failed: ${error.message}`);process.exit(1);});
